# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

 data:
    mongodb:
      host: localhost
      port: 27017
      database: bank
